import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';
import type { JourneyStateService } from './state';

/** Write a real document under .threedot/artifacts and open it. */
export async function writeArtifact(
  svc: JourneyStateService,
  key: string,
  filename: string,
  content: string,
  kind: string
): Promise<string | undefined> {
  const ws = vscode.workspace.workspaceFolders?.[0];
  if (!ws) {
    void vscode.window.showWarningMessage('3dot journey: open a folder first.');
    return undefined;
  }
  const dir = path.join(ws.uri.fsPath, '.threedot', 'artifacts');
  fs.mkdirSync(dir, { recursive: true });
  const full = path.join(dir, filename);
  fs.writeFileSync(full, content, 'utf8');
  svc.addArtifact(key, full, kind, content);
  const doc = await vscode.workspace.openTextDocument(full);
  await vscode.window.showTextDocument(doc, { preview: true, viewColumn: vscode.ViewColumn.Beside });
  return full;
}

export function integrationBriefMd(intent: Record<string, unknown>): string {
  return `# Integration Brief

> Grounded in CID + never-raise envelopes. Not a leap of faith.

| Field | Value |
|---|---|
| Objective | ${intent.objective ?? ''} |
| Counterparty class | ${intent.counterparty ?? ''} |
| Data direction | ${intent.direction ?? ''} |
| Sensitivity | ${intent.sensitivity ?? ''} |
| Expected proof | ${intent.proof ?? ''} |
| Outcome | ${intent.outcome ?? ''} |

## Gate
Next step unlocks only when objective, direction, and evidence criteria are explicit.

---
*Generated by threedot Cyborg Journey · altitude: mission*
`;
}

export function operationPlanMd(ops: Array<Record<string, unknown>>): string {
  const rows = ops.map((o) =>
    `| ${o.name} | ${o.direction ?? 'PULL'} | ${o.request ?? '—'} | ${o.response ?? '—'} | never-raise |`
  ).join('\n');
  return `# Operation Plan

Named operations with closed shapes and never-raise envelopes.

| Operation | Direction | Request | Response | Envelope |
|---|---|---|---|---|
${rows || '| _(none)_ | | | | |'}

## Diagnostics
Missing envelopes surface as diagnostics — never optimistic success.

---
*Generated by threedot Cyborg Journey · altitude: experience*
`;
}

export function cpcpPodYaml(title: string): string {
  return `# cpcp.pod.yaml — four-role boundary (reviewable)
# Preflight: no in-process jobs; FRONT/BACK role separation
apiVersion: cpcp/v1
kind: Pod
metadata:
  name: ${slug(title) || 'cpcp-pod'}
  labels:
    threedot.dev/journey: "true"
spec:
  roles:
    - name: FRONT
      image: cpcp/front:latest
      ports: [8080]
    - name: BACK
      image: cpcp/back:latest
      ports: [8081]
      env:
        CID_PATH: /_cpcp/cid.json
    - name: BackJob
      image: cpcp/backjob:latest
      # async only — never in-process with FRONT
    - name: GRAPH
      image: cpcp/graph:latest
  edges:
    - from: FRONT
      to: BACK
      protocol: json-rpc-ld
    - from: BACK
      to: BackJob
      protocol: queue
    - from: BACK
      to: GRAPH
      protocol: sparql
  preflight:
    noInProcessJobs: true
    cidBound: true
`;
}

export function interfacePromiseMd(p: Record<string, unknown>): string {
  return `# Interface Promise

| Field | Value |
|---|---|
| Promise | ${p.promise ?? ''} |
| Owner / action | ${p.owner ?? ''} |
| Eligibility | ${p.eligibility ?? ''} |
| Discovery | ${p.discovery ?? ''} |
| Disclosure | ${p.disclosure ?? ''} |

No service is bound until CID-binding occurs.

---
*Generated by threedot Cyborg Journey · altitude: mission · persona: javascript*
`;
}

export function frontDoorMd(): string {
  return `# Front Door State Machine

States (never-raise envelope-aware):

1. **idle** — no offer extended
2. **discovering** — scape query in flight
3. **qualified** — candidate with provenance
4. **unavailable** — envelope: capability missing
5. **pending** — awaiting human / pair
6. **envelope-return** — structured failure (ok:false)
7. **resolved** — success envelope bound to CID op

UI must render every envelope state; never leak stack traces.

---
*Generated by threedot Cyborg Journey · altitude: experience*
`;
}

export function bindingMatrixMd(ops: Array<Record<string, unknown>>): string {
  const rows = ops.map((o) => `| ${o.name} | ${o.cidOp ?? o.name} | bound |`).join('\n');
  return `# Binding Matrix

| UI action | CID operation | Status |
|---|---|---|
${rows || '| _(define operations first)_ | | |'}

Diagnostics warn on unknown shapes or missing envelopes.

---
*Generated by threedot Cyborg Journey · altitude: engineering*
`;
}

export function releaseEvidenceMd(state: {
  persona: string;
  journeyId: string;
  steps: string[];
  verify?: string;
  cid?: string;
}): string {
  return `# Release Evidence

| Field | Value |
|---|---|
| Journey | ${state.journeyId} |
| Persona | ${state.persona} |
| CID | ${state.cid ?? '(default or workspace)'} |
| Verify | ${state.verify ?? 'pending'} |

## Completed gates
${state.steps.map((s) => `- [x] ${s}`).join('\n') || '- _(none)_'}

## Grounding
- CID-bound capabilities
- Never-raise envelopes throughout
- mmg-scape qualification (when applicable)
- CPCP four-role boundary (Rails) / front-door surface (JS)

Release readiness requires successful deploy + verify when claimed.

---
*Generated by threedot Cyborg Journey · mission/experience close*
`;
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 48);
}
