# frozen_string_literal: true
# MagenticMarket-Copyright-Notice: begin v1
# SPDX-FileCopyrightText: 2026 CBI Business Transactions, LLC
# SPDX-License-Identifier: LicenseRef-DataYoursSoftwareMine-1.0
# SPDX-FileComment: License-URL: https://github.com/laquereric/DataYoursSoftwareMine
# MagenticMarket-Copyright-Notice: end v1

require "fileutils"
require "vv/mobile"

module Vv
  module Android
    # Emits a Swift dynamic library for the official Swift 6.3 Android SDK.
    # Re-exports the vv-mobile shared kit and pins a C ABI (`@c`) so Kotlin
    # can `System.loadLibrary` + JNI / swift-java jextract.
    #
    # Hard rule: NO SwiftUI. Android UI is Kotlin/Jetpack Compose.
    class Generator
      PACKAGE_DIR = "AndroidKit"
      ANDROID_SDK = Vv::Mobile::ANDROID_SDK

      def initialize(spec:, output_dir:)
        @spec = spec
        @output_dir = output_dir
      end

      def generate
        root = File.join(@output_dir, PACKAGE_DIR)
        sources = File.join(root, "Sources", PACKAGE_DIR)
        FileUtils.mkdir_p(sources)

        written = []
        written << write(File.join(root, "Package.swift"), package_swift)
        written << write(File.join(root, "README.md"), package_readme)
        written << write(File.join(sources, "Reexport.swift"), reexport_swift)
        written << write(File.join(sources, "CBridge.swift"), c_bridge_swift)
        written << write(File.join(sources, "ModelPins.swift"), model_pins_swift)
        written << write(File.join(sources, "CatalogPins.swift"), catalog_pins_swift)

        forbidden = ["import SwiftUI", "import UIKit", "import AppKit"]
        written.select { |path| path.end_with?(".swift") }.each do |path|
          body = File.read(path)
          hit = forbidden.find { |token| body.include?(token) }
          if hit
            return { ok: false, reason: "ui_leak", because: "#{path} contains #{hit.inspect} — Android kit is JNI/Swift, not SwiftUI" }
          end
        end

        { ok: true, written: written.sort, count: written.size, package_dir: root, android_sdk: ANDROID_SDK }
      rescue SystemCallError => e
        { ok: false, reason: "io_error", because: e.message }
      end

      private

      def write(path, contents)
        FileUtils.mkdir_p(File.dirname(path))
        File.write(path, contents)
        path
      end

      def kit
        @spec.module_name
      end

      def header(note)
        <<~SWIFT
          // Generated by vv-android #{Vv::Android::VERSION}. Do not edit by hand.
          // #{note}
          #{Vv::Mobile::Copyright::SWIFT}

        SWIFT
      end

      def package_swift
        <<~SWIFT
          // swift-tools-version: 6.3
          #{Vv::Mobile::Copyright::SWIFT}
          // Generated by vv-android #{Vv::Android::VERSION}.
          // Android dynamic library over the vv-mobile shared package.
          // Cross-compile:
          //   swift build --swift-sdk #{ANDROID_SDK}
          // NO SwiftUI. Kotlin/Jetpack Compose owns the view hierarchy.
          // Kotlin talks to this .so via Swift Java / JNI Core (jextract)
          // or the @c pins in CBridge.swift.

          import PackageDescription

          let package = Package(
              name: "#{PACKAGE_DIR}",
              platforms: [
                  .iOS(.v17),
                  .macOS(.v14)
              ],
              products: [
                  .library(
                      name: "#{PACKAGE_DIR}",
                      type: .dynamic,
                      targets: ["#{PACKAGE_DIR}"]
                  )
              ],
              dependencies: [
                  .package(path: "../#{kit}")
              ],
              targets: [
                  .target(
                      name: "#{PACKAGE_DIR}",
                      dependencies: [
                          .product(name: "#{kit}", package: "#{kit}")
                      ]
                  )
              ]
          )
        SWIFT
      end

      def package_readme
        models = @spec.models.map { |m| m["name"] }.join(", ")
        <<~MD
          # #{PACKAGE_DIR}

          Generated by **vv-android** #{Vv::Android::VERSION}. Swift dynamic
          library for the official Swift 6.3 Android SDK.

          This is **not** SwiftUI-on-Android. UI is Kotlin/Jetpack Compose.
          This package re-exports `#{kit}` (models: #{models}) and pins a
          C ABI so Kotlin can load the `.so`.

          ## Build

          ```bash
          swift sdk install <swift-6.3-android-sdk.artifactbundle.tar.gz>
          vv-mobile generate spec.yml ./out
          vv-android generate spec.yml ./out
          swift build --package-path out/AndroidKit --swift-sdk #{ANDROID_SDK}
          ```

          Copy `.build/#{ANDROID_SDK}/release/libAndroidKit.so` into the
          Android app `jniLibs`.

          ## Call from Kotlin

          Prefer **swift-java jextract** on `#{kit}`'s public types (actors,
          models, Envelope). For bring-up without jextract:

          ```kotlin
          class SharedKit {
            companion object {
              init { System.loadLibrary("AndroidKit") }
              @JvmStatic external fun vv_android_abi_version(): Int
              @JvmStatic external fun vv_android_model_count(): Int
            }
          }
          ```

          The `@c` names in `CBridge.swift` / `ModelPins.swift` are the
          JNI symbols. Envelope JSON still uses `{ ok, value, reason, because }`.

          Skip is unofficial and is not required.
        MD
      end

      def reexport_swift
        header("One .so for Kotlin: re-export the shared kit so jextract sees a single module.") + <<~SWIFT
          @_exported import #{kit}
        SWIFT
      end

      def c_bridge_swift
        header("Swift 6.3 @c ABI. Load with System.loadLibrary(\"#{PACKAGE_DIR}\").") + <<~SWIFT
          import Foundation
          import #{kit}

          /// ABI version of this JNI/@c surface. Bump when pin signatures change.
          @c
          public func vv_android_abi_version() -> Int32 {
              1
          }

          /// Copies the shared-kit module name into `buffer`. Returns bytes written
          /// (excluding NUL), or -1 if `n` is too small.
          @c
          public func vv_android_module_name(_ buffer: UnsafeMutablePointer<CChar>?, _ n: Int32) -> Int32 {
              copyCString(#{kit.inspect}, into: buffer, n: n)
          }

          /// Number of generated domain models (so Kotlin can size arrays).
          @c
          public func vv_android_model_count() -> Int32 {
              #{@spec.models.size}
          }

          /// Copies Failure.reason + Failure.because style documentation into
          /// `buffer` so a Kotlin caller can print the envelope contract.
          @c
          public func vv_android_envelope_contract(_ buffer: UnsafeMutablePointer<CChar>?, _ n: Int32) -> Int32 {
              copyCString("ok|value / reason|because", into: buffer, n: n)
          }

          func copyCString(_ s: String, into buffer: UnsafeMutablePointer<CChar>?, n: Int32) -> Int32 {
              guard let buffer, n > 0 else { return -1 }
              var bytes = Array(s.utf8CString)
              if bytes.count > Int(n) { return -1 }
              buffer.update(from: &bytes, count: bytes.count)
              return Int32(s.utf8.count)
          }
        SWIFT
      end

      def model_pins_swift
        pins = @spec.models.each_with_index.map do |model, i|
          c_name = c_ident(model["name"])
          <<~SWIFT
            @c
            public func vv_android_model_#{c_name}_index() -> Int32 {
                #{i}
            }

            @c
            public func vv_android_model_#{c_name}_name(_ buffer: UnsafeMutablePointer<CChar>?, _ n: Int32) -> Int32 {
                copyCString(#{model["name"].inspect}, into: buffer, n: n)
            }
          SWIFT
        end.join("\n")
        header("Per-model @c pins. jextract on #{kit} is the preferred long-term path.") + <<~SWIFT
          import Foundation
          import #{kit}

          #{pins}
        SWIFT
      end

      def catalog_pins_swift
        acia = Vv::Mobile::Catalog::ACIA_COMPONENTS
        aiux = Vv::Mobile::Catalog::AIUX_INTENTIONS.map { |i| i["kind"] }
        header("Precompiled 19 ACIA + 12 AIUX catalog pins. Kotlin looks up; it does not invent kinds.") + <<~SWIFT
          import Foundation
          import #{kit}

          private let aciaKinds: [String] = [
              #{acia.map(&:inspect).join(",\n              ")}
          ]

          private let aiuxKinds: [String] = [
              #{aiux.map(&:inspect).join(",\n              ")}
          ]

          @c
          public func vv_android_acia_count() -> Int32 {
              Int32(AciaComponent.ghis19.count)
          }

          @c
          public func vv_android_aiux_count() -> Int32 {
              Int32(AiuxIntention.allCases.count)
          }

          @c
          public func vv_android_acia_kind(_ index: Int32, _ buffer: UnsafeMutablePointer<CChar>?, _ n: Int32) -> Int32 {
              guard index >= 0, index < aciaKinds.count else { return -1 }
              return copyCString(aciaKinds[Int(index)], into: buffer, n: n)
          }

          @c
          public func vv_android_aiux_kind(_ index: Int32, _ buffer: UnsafeMutablePointer<CChar>?, _ n: Int32) -> Int32 {
              guard index >= 0, index < aiuxKinds.count else { return -1 }
              return copyCString(aiuxKinds[Int(index)], into: buffer, n: n)
          }

          @c
          public func vv_android_acia_contains(_ raw: UnsafePointer<CChar>?) -> Int32 {
              guard let raw else { return 0 }
              let name = String(cString: raw)
              return AciaComponent.inCatalog(name, version: .ghis19) == nil ? 0 : 1
          }

          @c
          public func vv_android_aiux_contains(_ raw: UnsafePointer<CChar>?) -> Int32 {
              guard let raw else { return 0 }
              let name = String(cString: raw)
              return AiuxIntention(rawValue: name) == nil ? 0 : 1
          }
        SWIFT
      end

      def c_ident(name)
        name.gsub(/[^A-Za-z0-9]/, "_").downcase
      end
    end
  end
end
