# frozen_string_literal: true

require "bundler/setup"
require "rake"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)
task default: :spec

load File.expand_path("tasks/vv_per_site.rake", __dir__)
