# frozen_string_literal: true
# MagenticMarket-Copyright-Notice: begin v1
# SPDX-FileCopyrightText: 2026 CBI Business Transactions, LLC
# SPDX-License-Identifier: LicenseRef-DataYoursSoftwareMine-1.0
# SPDX-FileComment: License-URL: https://github.com/laquereric/DataYoursSoftwareMine
# MagenticMarket-Copyright-Notice: end v1

require "fileutils"
require_relative "copyright"
require_relative "spec"
require_relative "catalog"

module Vv
  module Mobile
    # Emits a Foundation-only Swift package that compiles for iOS *and*
    # Android (`swift build --swift-sdk aarch64-unknown-linux-android28`).
    #
    # Hard rules (docs/research/Swift.md / Swift 6.3 Android SDK):
    #   - NO SwiftUI, NO UIKit, NO AppKit, NO Jetpack Compose
    #   - Codable + Sendable models, actor repositories, async/await URLSession
    #   - never-raise Envelope matching MM { ok / reason / because }
    class Generator
      ANDROID_SDK = "aarch64-unknown-linux-android28"
      PACKAGE_DIR = "SharedKit"

      def initialize(spec:, output_dir:)
        @spec = spec
        @output_dir = output_dir
      end

      def generate
        root = File.join(@output_dir, PACKAGE_DIR)
        sources = File.join(root, "Sources", @spec.module_name)
        FileUtils.mkdir_p(File.join(sources, "Models"))
        FileUtils.mkdir_p(File.join(sources, "Repositories"))
        FileUtils.mkdir_p(File.join(sources, "Networking"))
        FileUtils.mkdir_p(File.join(sources, "Acia"))
        FileUtils.mkdir_p(File.join(root, "Tests", "#{@spec.module_name}Tests"))

        written = []
        written << write(File.join(root, "Package.swift"), package_swift)
        written << write(File.join(root, "README.md"), package_readme)
        written << write(File.join(sources, "Envelope.swift"), envelope_swift)
        written << write(File.join(sources, "Acia", "Catalog.swift"), catalog_swift)
        written << write(File.join(sources, "Acia", "AciaNode.swift"), acia_node_swift)
        written << write(File.join(sources, "Acia", "AiuxCompiler.swift"), compiler_swift)
        written << write(File.join(sources, "Networking", "HTTPClient.swift"), http_client_swift)
        @spec.models.each do |model|
          written << write(File.join(sources, "Models", "#{model["name"]}.swift"), model_swift(model))
        end
        @spec.repositories.each do |repo|
          written << write(File.join(sources, "Repositories", "#{repo["name"]}.swift"), repository_swift(repo))
        end
        written << write(
          File.join(root, "Tests", "#{@spec.module_name}Tests", "DecodeTests.swift"),
          decode_tests_swift
        )
        written << write(
          File.join(root, "Tests", "#{@spec.module_name}Tests", "CatalogTests.swift"),
          catalog_tests_swift
        )

        forbidden = ["import SwiftUI", "import UIKit", "import AppKit", "import AndroidView"]
        written.select { |path| path.end_with?(".swift") }.each do |path|
          body = File.read(path)
          hit = forbidden.find { |token| body.include?(token) }
          if hit
            return { ok: false, reason: "ui_leak", because: "#{path} contains #{hit.inspect} — shared kit is logic-only" }
          end
        end

        { ok: true, written: written.sort, count: written.size, package_dir: root, android_sdk: ANDROID_SDK }
      rescue SystemCallError => e
        { ok: false, reason: "io_error", because: e.message }
      end

      private

      def write(path, contents)
        FileUtils.mkdir_p(File.dirname(path))
        File.write(path, contents)
        path
      end

      def header(generated_note)
        <<~SWIFT
          // Generated by vv-mobile #{Vv::Mobile::VERSION}. Do not edit by hand.
          // #{generated_note}
          #{Copyright::SWIFT}

        SWIFT
      end

      def package_swift
        <<~SWIFT
          // swift-tools-version: 6.3
          #{Copyright::SWIFT}
          // Generated by vv-mobile #{Vv::Mobile::VERSION}.
          // Shared logic package: compiles for Apple platforms AND the official
          // Swift 6.3 Android SDK. Cross-compile:
          //   swift build --swift-sdk #{ANDROID_SDK}
          // This package MUST remain UI-free (no view frameworks).

          import PackageDescription

          let package = Package(
              name: "#{@spec.module_name}",
              platforms: [
                  .iOS(.v17),
                  .macOS(.v14)
              ],
              products: [
                  .library(
                      name: "#{@spec.module_name}",
                      type: .dynamic,
                      targets: ["#{@spec.module_name}"]
                  )
              ],
              targets: [
                  .target(
                      name: "#{@spec.module_name}"
                  ),
                  .testTarget(
                      name: "#{@spec.module_name}Tests",
                      dependencies: ["#{@spec.module_name}"]
                  )
              ]
          )
        SWIFT
      end

      def package_readme
        <<~MD
          # #{@spec.module_name}

          Generated by **vv-mobile** #{Vv::Mobile::VERSION}. Shared Swift business
          logic — models, repositories, networking, and the **precompiled**
          12 AIUX intentions + 19 ACIA (`ghis-19@1`) widgets — for iOS **and** Android.

          This is **not** SwiftUI-on-Android. The official Swift 6.3 Android SDK
          ships a native compiler target + Swift-Java/JNI. UI stays on the
          platform shells (`vv-ios` SwiftUI, Kotlin/Jetpack Compose on Android).

          ## Build

          ```bash
          swift build
          swift build --swift-sdk #{ANDROID_SDK}
          ```

          ## Doctrine

          - `Foundation` only. No `import SwiftUI`.
          - Models are `Codable, Sendable`. Repositories are `actor`s.
          - Failures return `Envelope.fail(Failure(reason:because:))` — never throw
            across the platform boundary.
        MD
      end

      def envelope_swift
        header("Never-raise envelope. Mirrors MM { ok: true } / { ok: false, reason:, because: }.") + <<~SWIFT
          import Foundation

          public struct Failure: Sendable, Codable, Equatable {
              public let reason: String
              public let because: String

              public init(reason: String, because: String) {
                  self.reason = reason
                  self.because = because
              }
          }

          public enum Envelope<T: Sendable>: Sendable {
              case ok(T)
              case fail(Failure)

              public var isOk: Bool {
                  if case .ok = self { return true }
                  return false
              }
          }

          extension Envelope: Codable where T: Codable {
              private enum CodingKeys: String, CodingKey {
                  case ok, value, reason, because
              }

              public init(from decoder: Decoder) throws {
                  let c = try decoder.container(keyedBy: CodingKeys.self)
                  if try c.decode(Bool.self, forKey: .ok) {
                      self = .ok(try c.decode(T.self, forKey: .value))
                  } else {
                      self = .fail(Failure(
                          reason: try c.decode(String.self, forKey: .reason),
                          because: try c.decode(String.self, forKey: .because)
                      ))
                  }
              }

              public func encode(to encoder: Encoder) throws {
                  var c = encoder.container(keyedBy: CodingKeys.self)
                  switch self {
                  case .ok(let value):
                      try c.encode(true, forKey: .ok)
                      try c.encode(value, forKey: .value)
                  case .fail(let failure):
                      try c.encode(false, forKey: .ok)
                      try c.encode(failure.reason, forKey: .reason)
                      try c.encode(failure.because, forKey: .because)
                  }
              }
          }
        SWIFT
      end

      def http_client_swift
        header("URLSession client. Same code on iOS and Android Swift SDK.") + <<~SWIFT
          import Foundation

          public actor HTTPClient: Sendable {
              public let baseURL: URL

              public init(baseURL: URL) {
                  self.baseURL = baseURL
              }

              public init(baseURLString: String) {
                  self.baseURL = URL(string: baseURLString) ?? URL(string: "https://invalid.invalid")!
              }

              public func get<T: Decodable & Sendable>(_ path: String) async -> Envelope<T> {
                  let url: URL
                  if let composed = URL(string: path, relativeTo: baseURL) {
                      url = composed.absoluteURL
                  } else {
                      return .fail(Failure(reason: "bad_url", because: "Could not join \\(baseURL) with \\(path)"))
                  }
                  do {
                      let (data, response) = try await URLSession.shared.data(from: url)
                      if let http = response as? HTTPURLResponse, !(200...299).contains(http.statusCode) {
                          return .fail(Failure(
                              reason: "http_\\(http.statusCode)",
                              because: "GET \\(url.absoluteString) returned \\(http.statusCode)"
                          ))
                      }
                      let decoded = try JSONDecoder().decode(T.self, from: data)
                      return .ok(decoded)
                  } catch {
                      return .fail(Failure(reason: "network", because: error.localizedDescription))
                  }
              }
          }
        SWIFT
      end

      def model_swift(model)
        name = model["name"]
        props = @spec.properties_for(model)
        fields = props.map { |p| "    public let #{p["name"]}: #{p["type"]}" }.join("\n")
        inits = props.map { |p| "        self.#{p["name"]} = #{p["name"]}" }.join("\n")
        params = props.map { |p| "#{p["name"]}: #{p["type"]}" }.join(", ")
        header("Shared domain model. Compiles for iOS and #{ANDROID_SDK}.") + <<~SWIFT
          import Foundation

          public struct #{name}: Codable, Sendable, Equatable, Hashable#{identifiable_suffix(props)} {
          #{fields}

              public init(#{params}) {
          #{inits}
              }
          }
        SWIFT
      end

      def repository_swift(repo)
        name = repo["name"]
        model = repo["model"]
        collection = repo["collection_path"] || "/#{model.downcase}s"
        member = repo["member_path"] || "#{collection}/{id}"
        header("Actor repository. Shared view-model brain — not a UI type.") + <<~SWIFT
          import Foundation

          public actor #{name}: Sendable {
              private let client: HTTPClient

              public init(client: HTTPClient) {
                  self.client = client
              }

              public init(baseURLString: String = #{@spec.base_url.inspect}) {
                  self.client = HTTPClient(baseURLString: baseURLString)
              }

              public func list() async -> Envelope<[#{model}]> {
                  await client.get(#{collection.inspect})
              }

              public func fetch(id: String) async -> Envelope<#{model}> {
                  let path = #{member.inspect}.replacingOccurrences(of: "{id}", with: id)
                  return await client.get(path)
              }
          }
        SWIFT
      end

      def decode_tests_swift
        first = @spec.models.first
        return header("No models to test.") + "import XCTest\n" unless first

        name = first["name"]
        props = @spec.properties_for(first)
        json_pairs = props.map { |p| sample_json_pair(p) }.join(", ")
        header("Decode round-trip for generated models.") + <<~SWIFT
          import XCTest
          @testable import #{@spec.module_name}

          final class DecodeTests: XCTestCase {
              func test#{name}Decodes() throws {
                  let json = Data("{#{json_pairs}}".utf8)
                  let value = try JSONDecoder().decode(#{name}.self, from: json)
                  XCTAssertNotNil(value)
              }
          }
        SWIFT
      end

      def catalog_swift
        acia_cases = Catalog::ACIA_COMPONENTS.map { |k| "    case #{swift_enum_case(k)} = #{k.inspect}" }.join("\n")
        bump20 = "    case dateInput = \"DateInput\""
        bump21 = "    case input = \"Input\""
        aiux_cases = Catalog::AIUX_INTENTIONS.map { |i|
          "    case #{swift_enum_case(i["kind"])} = #{i["kind"].inspect}"
        }.join("\n")
        composed = Catalog::AIUX_INTENTIONS.map { |i|
          kinds = i["composedOf"].map { |c| ".#{swift_enum_case(c)}" }.join(", ")
          "        case .#{swift_enum_case(i["kind"])}: return [#{kinds}]"
        }.join("\n")
        jobs = Catalog::AIUX_INTENTIONS.map { |i|
          "        case .#{swift_enum_case(i["kind"])}: return #{i["job"].inspect}"
        }.join("\n")
        versions = Catalog::AIUX_INTENTIONS.map { |i|
          "        case .#{swift_enum_case(i["kind"])}: return #{i["catalogVersion"].inspect}"
        }.join("\n")
        header("Closed catalogs: 19 ACIA widgets (ghis-19@1) + 12 AIUX intentions. Precompiled into the client.") + <<~SWIFT
          import Foundation

          public enum CatalogVersion: String, Sendable, Codable, CaseIterable {
              case ghis19 = "#{Catalog::GHIS_19}"
              case ghis20 = "#{Catalog::GHIS_20}"
              case ghis21 = "#{Catalog::GHIS_21}"
          }

          /// 19 ACIA presentation widgets. Closed. Unknown kind refuses.
          public enum AciaComponent: String, Sendable, Codable, CaseIterable {
          #{acia_cases}
          #{bump20}
          #{bump21}

              public static var ghis19: [AciaComponent] {
                  allCases.filter { $0 != .dateInput && $0 != .input }
              }

              public static func inCatalog(_ raw: String, version: CatalogVersion = .ghis19) -> AciaComponent? {
                  guard let kind = AciaComponent(rawValue: raw) else { return nil }
                  switch version {
                  case .ghis19:
                      return (kind == .dateInput || kind == .input) ? nil : kind
                  case .ghis20:
                      return kind == .input ? nil : kind
                  case .ghis21:
                      return kind
                  }
              }
          }

          /// 12 AIUX intentions — jobs an agent puts in front of a human.
          public enum AiuxIntention: String, Sendable, Codable, CaseIterable {
          #{aiux_cases}

              public var job: String {
                  switch self {
          #{jobs}
                  }
              }

              public var catalogVersion: CatalogVersion {
                  switch self {
          #{versions}
                  }
              }

              /// First element is always PageShell (the document root).
              public var composedOf: [AciaComponent] {
                  switch self {
          #{composed}
                  }
              }
          }
        SWIFT
      end

      def acia_node_swift
        header("ACIA document node. The agent names kinds the client already shipped.") + <<~SWIFT
          import Foundation

          public struct AciaSLT: Codable, Sendable, Equatable {
              public var semanticRole: String
              public var contentRole: String
              public var layoutKind: String
              public var layoutArity: String
              public var behaviorKind: String

              public init(semanticRole: String = "landmark", contentRole: String = "context",
                          layoutKind: String = "stack", layoutArity: String = "one",
                          behaviorKind: String = "static") {
                  self.semanticRole = semanticRole
                  self.contentRole = contentRole
                  self.layoutKind = layoutKind
                  self.layoutArity = layoutArity
                  self.behaviorKind = behaviorKind
              }
          }

          public struct AciaNode: Codable, Sendable, Equatable {
              public var nodeId: String
              public var componentKind: String
              public var slt: AciaSLT
              public var value: [String: String]
              public var children: [AciaNode]

              public init(nodeId: String, componentKind: String, slt: AciaSLT = AciaSLT(),
                          value: [String: String] = [:], children: [AciaNode] = []) {
                  self.nodeId = nodeId
                  self.componentKind = componentKind
                  self.slt = slt
                  self.value = value
                  self.children = children
              }

              public func string(_ key: String) -> String {
                  value[key] ?? ""
              }
          }

          public struct AciaDocument: Codable, Sendable, Equatable {
              public var schemaVersion: String
              public var componentRegistryVersion: String
              public var root: AciaNode

              public init(schemaVersion: String = "acia/v1",
                          componentRegistryVersion: String = CatalogVersion.ghis19.rawValue,
                          root: AciaNode) {
                  self.schemaVersion = schemaVersion
                  self.componentRegistryVersion = componentRegistryVersion
                  self.root = root
              }
          }

          public struct AiuxCompileRequest: Sendable {
              public var taskKind: String
              public var title: String
              public var fields: [[String: String]]
              public var blobDigest: String
              public var catalogVersion: String

              public init(taskKind: String, title: String = "", fields: [[String: String]] = [],
                          blobDigest: String = "", catalogVersion: String = "") {
                  self.taskKind = taskKind
                  self.title = title
                  self.fields = fields
                  self.blobDigest = blobDigest
                  self.catalogVersion = catalogVersion
              }
          }
        SWIFT
      end

      def compiler_swift
        header("F4 compile: AIUX intention → ACIA. Deterministic. Date never compiles to text.") + <<~SWIFT
          import Foundation

          public enum AiuxCompiler: Sendable {
              public static func compile(_ request: AiuxCompileRequest) -> Envelope<AciaDocument> {
                  guard let intention = AiuxIntention(rawValue: request.taskKind) else {
                      return .fail(Failure(
                          reason: "kind_not_in_catalog",
                          because: "taskKind \\(request.taskKind) is not one of the 12 AIUX intentions"
                      ))
                  }
                  let version: CatalogVersion
                  if request.catalogVersion.isEmpty {
                      version = intention.catalogVersion
                  } else if let parsed = CatalogVersion(rawValue: request.catalogVersion) {
                      version = parsed
                  } else {
                      return .fail(Failure(reason: "kind_not_in_catalog", because: "unknown catalogVersion"))
                  }
                  if intention == .date && version == .ghis19 {
                      return .fail(Failure(
                          reason: "date_kind_missing",
                          because: "date does not compile to text; needs ghis-20@1 DateInput"
                      ))
                  }
                  if intention == .form && request.fields.isEmpty {
                      return .fail(Failure(reason: "information_model_required", because: "task.form requires fields"))
                  }
                  if intention == .preview {
                      let digest = request.blobDigest
                      let ok = digest.hasPrefix("sha256:") && digest.dropFirst(7).count == 64
                          && digest.dropFirst(7).allSatisfy { $0.isHexDigit }
                      if !ok {
                          return .fail(Failure(
                              reason: "blob_digest_required",
                              because: "task.preview requires blobDigest sha256:<64 hex>"
                          ))
                      }
                  }
                  let composed = intention.composedOf
                  for kind in composed {
                      if AciaComponent.inCatalog(kind.rawValue, version: version) == nil {
                          return .fail(Failure(
                              reason: "kind_not_in_catalog",
                              because: "\\(kind.rawValue) is not in \\(version.rawValue)"
                          ))
                      }
                  }
                  let title = request.title.isEmpty ? intention.rawValue : request.title
                  let childKinds = Array(composed.dropFirst())
                  var children: [AciaNode] = childKinds.map { kind in
                      AciaNode(
                          nodeId: "\\(kind.rawValue.lowercased())-1",
                          componentKind: kind.rawValue,
                          value: childValue(intention: intention, kind: kind, title: title, blobDigest: request.blobDigest)
                      )
                  }
                  if intention == .form {
                      children.append(contentsOf: request.fields.map { field in
                          let name = field["name"] ?? "field"
                          return AciaNode(
                              nodeId: "field-\\(name)",
                              componentKind: AciaComponent.decisionForm.rawValue,
                              value: ["field": name, "datatype": field["datatype"] ?? "string"]
                          )
                      })
                  }
                  let root = AciaNode(
                      nodeId: "page-shell-1",
                      componentKind: AciaComponent.pageShell.rawValue,
                      slt: AciaSLT(layoutArity: "many"),
                      value: ["title": title, "pagePurpose": intention.rawValue],
                      children: children
                  )
                  return .ok(AciaDocument(componentRegistryVersion: version.rawValue, root: root))
              }

              private static func childValue(intention: AiuxIntention, kind: AciaComponent,
                                             title: String, blobDigest: String) -> [String: String] {
                  switch kind {
                  case .emptyState: return ["text": "No rows"]
                  case .refusalNotice: return ["reason": "task-error", "operation": "report-error"]
                  case .semanticText:
                      if intention == .preview {
                          return ["text": blobDigest, "blobDigest": blobDigest]
                      }
                      return ["text": title]
                  case .actionControl: return ["action": "submit", "label": "Submit"]
                  case .dataList: return ["title": title]
                  case .statusBadge: return ["text": title, "state": "waiting"]
                  case .tabSet: return ["title": title]
                  case .timeline: return ["title": title]
                  case .referentBridge: return ["targetExpression": title]
                  case .dateInput: return ["field": "date", "datatype": "date"]
                  case .decisionForm: return ["field": "decision", "choices": "approve,deny"]
                  default: return ["kind": kind.rawValue]
                  }
              }
          }
        SWIFT
      end

      def catalog_tests_swift
        header("Closed catalog counts. The client already shipped these.") + <<~SWIFT
          import XCTest
          @testable import #{@spec.module_name}

          final class CatalogTests: XCTestCase {
              func testNineteenAciaComponents() {
                  XCTAssertEqual(AciaComponent.ghis19.count, 19)
              }

              func testTwelveAiuxIntentions() {
                  XCTAssertEqual(AiuxIntention.allCases.count, 12)
              }

              func testEmptyCompilesToEmptyState() {
                  let result = AiuxCompiler.compile(AiuxCompileRequest(taskKind: "task.empty"))
                  guard case .ok(let doc) = result else {
                      return XCTFail("expected ok")
                  }
                  XCTAssertEqual(doc.root.componentKind, "PageShell")
                  XCTAssertTrue(doc.root.children.contains { $0.componentKind == "EmptyState" })
              }

              func testDateOnGhis19Refuses() {
                  let result = AiuxCompiler.compile(
                      AiuxCompileRequest(taskKind: "task.date", catalogVersion: "ghis-19@1")
                  )
                  guard case .fail(let failure) = result else {
                      return XCTFail("expected refuse")
                  }
                  XCTAssertEqual(failure.reason, "date_kind_missing")
              }

              func testUnknownKindRefuses() {
                  let result = AiuxCompiler.compile(AiuxCompileRequest(taskKind: "task.draw"))
                  guard case .fail(let failure) = result else {
                      return XCTFail("expected refuse")
                  }
                  XCTAssertEqual(failure.reason, "kind_not_in_catalog")
              }
          }
        SWIFT
      end

      def swift_enum_case(name)
        core = name.sub(/\Atask\./, "")
        parts = core.split(/[^A-Za-z0-9]+/)
        return core if parts.empty?
        first = parts[0]
        rest = parts.drop(1).map { |p| p.capitalize }
        (first[0].downcase + first[1..] + rest.join)
      end

      def identifiable_suffix(props)
        props.any? { |p| p["name"] == "id" } ? ", Identifiable" : ""
      end

      def sample_json_pair(prop)
        type = prop["type"].to_s
        value = case type
                when "Int", "Int64", "Double" then "1"
                when "Bool" then "true"
                else "\\\"sample\\\""
                end
        "\\\"#{prop["name"]}\\\": #{value}"
      end
    end
  end
end
