# frozen_string_literal: true
# MagenticMarket-Copyright-Notice: begin v1
# SPDX-FileCopyrightText: 2026 CBI Business Transactions, LLC
# SPDX-License-Identifier: LicenseRef-DataYoursSoftwareMine-1.0
# SPDX-FileComment: License-URL: https://github.com/laquereric/DataYoursSoftwareMine
# MagenticMarket-Copyright-Notice: end v1

require "fileutils"
require "vv/mobile"

module Vv
  module Ios
    # Emits a SwiftUI iOS app that *consumes* the vv-mobile SharedKit package.
    # SwiftUI is legal here — this target never builds for Android.
    class Generator
      PACKAGE_DIR = "IosApp"

      def initialize(spec:, output_dir:)
        @spec = spec
        @output_dir = output_dir
      end

      def generate
        root = File.join(@output_dir, PACKAGE_DIR)
        sources = File.join(root, "Sources", PACKAGE_DIR)
        FileUtils.mkdir_p(File.join(sources, "Views"))
        FileUtils.mkdir_p(File.join(sources, "ViewModels"))
        FileUtils.mkdir_p(File.join(sources, "Acia"))

        written = []
        written << write(File.join(root, "Package.swift"), package_swift)
        written << write(File.join(root, "README.md"), package_readme)
        written << write(File.join(sources, "#{PACKAGE_DIR}App.swift"), app_swift)
        written << write(File.join(sources, "Acia", "AciaViews.swift"), acia_views_swift)
        written << write(File.join(sources, "Acia", "AciaRenderer.swift"), acia_renderer_swift)
        written << write(File.join(sources, "Acia", "TaskSlotView.swift"), task_slot_swift)
        written << write(File.join(sources, "Acia", "CatalogGalleryView.swift"), catalog_gallery_swift)
        @spec.models.each do |model|
          written << write(File.join(sources, "ViewModels", "#{model["name"]}ListModel.swift"), list_model_swift(model))
          written << write(File.join(sources, "Views", "#{model["name"]}ListView.swift"), list_view_swift(model))
          written << write(File.join(sources, "Views", "#{model["name"]}DetailView.swift"), detail_view_swift(model))
        end

        { ok: true, written: written.sort, count: written.size, package_dir: root }
      rescue SystemCallError => e
        { ok: false, reason: "io_error", because: e.message }
      end

      private

      def write(path, contents)
        FileUtils.mkdir_p(File.dirname(path))
        File.write(path, contents)
        path
      end

      def header(note)
        <<~SWIFT
          // Generated by vv-ios #{Vv::Ios::VERSION}. Do not edit by hand.
          // #{note}
          #{Vv::Mobile::Copyright::SWIFT}

        SWIFT
      end

      def kit
        @spec.module_name
      end

      def repo_for(model)
        @spec.repositories.find { |r| r["model"] == model["name"] }
      end

      def package_swift
        <<~SWIFT
          // swift-tools-version: 6.3
          #{Vv::Mobile::Copyright::SWIFT}
          // Generated by vv-ios #{Vv::Ios::VERSION}.
          // iOS / macOS SwiftUI shell. Depends on the vv-mobile shared package.
          // Apple-only — SwiftUI has no renderer on the official Swift SDK for Android.

          import PackageDescription

          let package = Package(
              name: "#{PACKAGE_DIR}",
              platforms: [
                  .iOS(.v17),
                  .macOS(.v14)
              ],
              products: [
                  .library(name: "#{PACKAGE_DIR}", targets: ["#{PACKAGE_DIR}"])
              ],
              dependencies: [
                  .package(path: "../#{kit}")
              ],
              targets: [
                  .target(
                      name: "#{PACKAGE_DIR}",
                      dependencies: [
                          .product(name: "#{kit}", package: "#{kit}")
                      ]
                  )
              ]
          )
        SWIFT
      end

      def package_readme
        <<~MD
          # #{PACKAGE_DIR}

          Generated by **vv-ios** #{Vv::Ios::VERSION}. SwiftUI shell over
          `#{kit}` (emitted by vv-mobile).

          This package is **Apple-only**. Android UI is Kotlin/Compose calling
          into the shared `.so` via `vv-android` — not SwiftUI, not Skip.

          ```bash
          # emit shared kit first
          vv-mobile generate spec.yml ./out
          vv-ios generate spec.yml ./out
          swift build --package-path out/IosApp
          ```
        MD
      end

      def app_swift
        first = @spec.models.first
        app_tab = first ? "#{first["name"]}ListView()" : "Text(\"#{kit}\")"
        header("SwiftUI @main. Precompiled 12 AIUX + 19 ACIA live in Catalog + TaskSlot tabs.") + <<~SWIFT
          import SwiftUI
          import #{kit}

          @main
          struct #{PACKAGE_DIR}App: App {
              var body: some Scene {
                  WindowGroup {
                      TabView {
                          NavigationStack { #{app_tab} }
                              .tabItem { Label("App", systemImage: "iphone") }
                          NavigationStack { CatalogGalleryView() }
                              .tabItem { Label("Catalog", systemImage: "square.grid.2x2") }
                          NavigationStack { TaskSlotView() }
                              .tabItem { Label("Task", systemImage: "checklist") }
                      }
                  }
              }
          }
        SWIFT
      end

      def acia_views_swift
        views = Vv::Mobile::Catalog::ACIA_COMPONENTS.map { |kind| acia_view_for(kind) }.join("\n")
        header("Precompiled SwiftUI for all 19 ghis-19@1 ACIA components.") + <<~SWIFT
          import SwiftUI
          import #{kit}

          #{views}
        SWIFT
      end

      def acia_view_for(kind)
        case kind
        when "PageShell"
          <<~SWIFT
            public struct PageShellView: View {
                public let node: AciaNode
                public init(node: AciaNode) { self.node = node }
                public var body: some View {
                    VStack(alignment: .leading, spacing: 12) {
                        Text(node.string("title")).font(.title2).bold()
                        AciaChildrenView(nodes: node.children)
                    }
                    .padding()
                    .navigationTitle(node.string("title"))
                }
            }
          SWIFT
        when "RefusalNotice"
          <<~SWIFT
            public struct RefusalNoticeView: View {
                public let node: AciaNode
                public init(node: AciaNode) { self.node = node }
                public var body: some View {
                    ContentUnavailableView(
                        node.string("reason").isEmpty ? "Refused" : node.string("reason"),
                        systemImage: "exclamationmark.triangle",
                        description: Text(node.string("operation"))
                    )
                }
            }
          SWIFT
        when "EmptyState"
          <<~SWIFT
            public struct EmptyStateView: View {
                public let node: AciaNode
                public init(node: AciaNode) { self.node = node }
                public var body: some View {
                    ContentUnavailableView(node.string("text").isEmpty ? "No rows" : node.string("text"),
                                           systemImage: "tray")
                }
            }
          SWIFT
        when "ActionControl"
          <<~SWIFT
            public struct ActionControlView: View {
                public let node: AciaNode
                public init(node: AciaNode) { self.node = node }
                public var body: some View {
                    Button(node.string("label").isEmpty ? "Submit" : node.string("label")) { }
                        .buttonStyle(.borderedProminent)
                }
            }
          SWIFT
        when "SemanticText"
          <<~SWIFT
            public struct SemanticTextView: View {
                public let node: AciaNode
                public init(node: AciaNode) { self.node = node }
                public var body: some View {
                    Text(node.string("text")).font(.body)
                }
            }
          SWIFT
        when "StatusBadge"
          <<~SWIFT
            public struct StatusBadgeView: View {
                public let node: AciaNode
                public init(node: AciaNode) { self.node = node }
                public var body: some View {
                    Label(node.string("text"), systemImage: "circle.fill")
                        .font(.caption)
                }
            }
          SWIFT
        when "DataList"
          <<~SWIFT
            public struct DataListView: View {
                public let node: AciaNode
                public init(node: AciaNode) { self.node = node }
                public var body: some View {
                    VStack(alignment: .leading) {
                        Text(node.string("title")).font(.headline)
                        AciaChildrenView(nodes: node.children)
                    }
                }
            }
          SWIFT
        when "DecisionForm"
          <<~SWIFT
            public struct DecisionFormView: View {
                public let node: AciaNode
                public init(node: AciaNode) { self.node = node }
                public var body: some View {
                    Form {
                        LabeledContent("Field", value: node.string("field"))
                        LabeledContent("Choices", value: node.string("choices"))
                    }
                }
            }
          SWIFT
        when "TabSet"
          <<~SWIFT
            public struct TabSetView: View {
                public let node: AciaNode
                public init(node: AciaNode) { self.node = node }
                public var body: some View {
                    Text(node.string("title")).font(.headline)
                }
            }
          SWIFT
        when "Timeline"
          <<~SWIFT
            public struct TimelineView: View {
                public let node: AciaNode
                public init(node: AciaNode) { self.node = node }
                public var body: some View {
                    Label(node.string("title"), systemImage: "timeline.selection")
                }
            }
          SWIFT
        when "ReferentBridge"
          <<~SWIFT
            public struct ReferentBridgeView: View {
                public let node: AciaNode
                public init(node: AciaNode) { self.node = node }
                public var body: some View {
                    Text(node.string("targetExpression")).font(.callout)
                }
            }
          SWIFT
        else
          <<~SWIFT
            public struct #{kind}View: View {
                public let node: AciaNode
                public init(node: AciaNode) { self.node = node }
                public var body: some View {
                    GroupBox(#{kind.inspect}) {
                        AciaChildrenView(nodes: node.children)
                    }
                }
            }
          SWIFT
        end
      end

      def acia_renderer_swift
        cases = Vv::Mobile::Catalog::ACIA_COMPONENTS.map { |kind|
          "            case #{kind.inspect}: #{kind}View(node: node)"
        }.join("\n")
        header("Dispatch ACIA node → precompiled SwiftUI widget. Unknown kind is RefusalNotice.") + <<~SWIFT
          import SwiftUI
          import #{kit}

          public struct AciaRenderer: View {
              public let node: AciaNode
              public init(node: AciaNode) { self.node = node }

              public var body: some View {
                  switch node.componentKind {
          #{cases}
                  default:
                      RefusalNoticeView(node: AciaNode(
                          nodeId: "unknown",
                          componentKind: "RefusalNotice",
                          value: ["reason": "kind_not_in_catalog", "operation": node.componentKind]
                      ))
                  }
              }
          }

          public struct AciaChildrenView: View {
              public let nodes: [AciaNode]
              public init(nodes: [AciaNode]) { self.nodes = nodes }
              public var body: some View {
                  ForEach(nodes, id: \\.nodeId) { child in
                      AciaRenderer(node: child)
                  }
              }
          }
        SWIFT
      end

      def task_slot_swift
        header("Task overlay. Compiles a named AIUX intention into ghis-19 and draws it.") + <<~SWIFT
          import SwiftUI
          import #{kit}

          public struct TaskSlotView: View {
              @State private var kind: AiuxIntention = .empty
              @State private var document: AciaDocument?
              @State private var failure: Failure?

              public init() {}

              public var body: some View {
                  VStack(alignment: .leading, spacing: 12) {
                      Picker("Intention", selection: $kind) {
                          ForEach(AiuxIntention.allCases, id: \\.self) { item in
                              Text(item.rawValue).tag(item)
                          }
                      }
                      .onChange(of: kind) { _, _ in compile() }
                      if let failure {
                          ContentUnavailableView(failure.reason, systemImage: "xmark.octagon",
                                                 description: Text(failure.because))
                      } else if let document {
                          AciaRenderer(node: document.root)
                      }
                  }
                  .padding()
                  .navigationTitle("Task slot")
                  .onAppear { compile() }
              }

              private func compile() {
                  var request = AiuxCompileRequest(taskKind: kind.rawValue)
                  if kind == .form {
                      request.fields = [["name": "decision", "datatype": "enum"]]
                  }
                  if kind == .preview {
                      request.blobDigest = "sha256:" + String(repeating: "ab", count: 32)
                  }
                  switch AiuxCompiler.compile(request) {
                  case .ok(let doc):
                      document = doc
                      failure = nil
                  case .fail(let f):
                      document = nil
                      failure = f
                  }
              }
          }
        SWIFT
      end

      def catalog_gallery_swift
        header("Proof the client already shipped 12 + 19. Not a drawing palette.") + <<~SWIFT
          import SwiftUI
          import #{kit}

          public struct CatalogGalleryView: View {
              public init() {}

              public var body: some View {
                  List {
                      Section("12 AIUX intentions") {
                          ForEach(AiuxIntention.allCases, id: \\.self) { item in
                              VStack(alignment: .leading) {
                                  Text(item.rawValue).font(.headline)
                                  Text(item.job).font(.caption).foregroundStyle(.secondary)
                              }
                          }
                      }
                      Section("19 ACIA components (ghis-19@1)") {
                          ForEach(AciaComponent.ghis19, id: \\.self) { item in
                              Text(item.rawValue)
                          }
                      }
                  }
                  .navigationTitle("Catalog")
              }
          }
        SWIFT
      end

      def list_model_swift(model)
        name = model["name"]
        repo = repo_for(model)
        repo_type = repo ? repo["name"] : "#{name}Repository"
        header("@MainActor ObservableObject wrapping the shared actor repository.") + <<~SWIFT
          import Foundation
          import Observation
          import #{kit}

          @Observable
          @MainActor
          public final class #{name}ListModel {
              public var items: [#{name}] = []
              public var failure: Failure?
              public var loading = false
              private let repository: #{repo_type}

              public init(repository: #{repo_type}) {
                  self.repository = repository
              }

              public func load() async {
                  loading = true
                  defer { loading = false }
                  switch await repository.list() {
                  case .ok(let items):
                      self.items = items
                      self.failure = nil
                  case .fail(let failure):
                      self.failure = failure
                  }
              }
          }
        SWIFT
      end

      def list_view_swift(model)
        name = model["name"]
        props = @spec.properties_for(model)
        title_prop = props.find { |p| p["name"] == "name" } || props.first
        subtitle_prop = props.find { |p| p["name"] == "id" }
        title_expr = title_prop ? "item.#{title_prop["name"]}" : "String(describing: item)"
        subtitle = subtitle_prop ? "Text(item.#{subtitle_prop["name"]}).font(.caption).foregroundStyle(.secondary)" : ""
        repo = repo_for(model)
        repo_type = repo ? repo["name"] : "#{name}Repository"
        header("SwiftUI list. Consumes SharedKit Envelope — never unwraps throws.") + <<~SWIFT
          import SwiftUI
          import #{kit}

          public struct #{name}ListView: View {
              @State private var model: #{name}ListModel

              public init() {
                  _model = State(initialValue: #{name}ListModel(repository: #{repo_type}()))
              }

              public var body: some View {
                  Group {
                      if model.loading && model.items.isEmpty {
                          ProgressView()
                      } else if let failure = model.failure, model.items.isEmpty {
                          ContentUnavailableView(
                              failure.reason,
                              systemImage: "exclamationmark.triangle",
                              description: Text(failure.because)
                          )
                      } else {
                          List(model.items) { item in
                              NavigationLink {
                                  #{name}DetailView(item: item)
                              } label: {
                                  VStack(alignment: .leading) {
                                      Text(#{title_expr})
                                      #{subtitle}
                                  }
                              }
                          }
                      }
                  }
                  .navigationTitle("#{name}s")
                  .task { await model.load() }
                  .refreshable { await model.load() }
              }
          }
        SWIFT
      end

      def detail_view_swift(model)
        name = model["name"]
        rows = @spec.properties_for(model).map do |p|
          "                LabeledContent(#{p["name"].inspect}) { Text(String(describing: item.#{p["name"]})) }"
        end.join("\n")
        header("SwiftUI detail. Read-only projection of a shared model.") + <<~SWIFT
          import SwiftUI
          import #{kit}

          public struct #{name}DetailView: View {
              public let item: #{name}

              public init(item: #{name}) {
                  self.item = item
              }

              public var body: some View {
                  Form {
          #{rows}
                  }
                  .navigationTitle("#{name}")
              }
          }
        SWIFT
      end
    end
  end
end
