# frozen_string_literal: true

require_relative "rails_osi_level_8/version"
require_relative "rails_osi_level_8/envelope"
require_relative "rails_osi_level_8/known_refusal"
require_relative "rails_osi_level_8/configuration"
require_relative "rails_osi_level_8/cid"
require_relative "rails_osi_level_8/ledger"
require_relative "rails_osi_level_8/ledger_policy"
require_relative "rails_osi_level_8/profile_catalog"
require_relative "rails_osi_level_8/grounding"
require_relative "rails_osi_level_8/grammar"
require_relative "rails_osi_level_8/profile9/vocabulary"
require_relative "rails_osi_level_8/profile9/contract"
require_relative "rails_osi_level_8/profile9/acia"
require_relative "rails_osi_level_8/profile9/translation_board"
require_relative "rails_osi_level_8/profile9/renderer"
require_relative "rails_osi_level_8/profile9/request"
require_relative "rails_osi_level_8/profile9/graph"
require_relative "rails_osi_level_8/profile9/pulls"
require_relative "rails_osi_level_8/profile9/design_gate"
require_relative "rails_osi_level_8/profile9/mutations"
require_relative "rails_osi_level_8/profile9/host_layout"
require_relative "rails_osi_level_8/profile11/vocabulary"
require_relative "rails_osi_level_8/profile11/request"
require_relative "rails_osi_level_8/profile11/contract"
require_relative "rails_osi_level_8/profile11/store"
require_relative "rails_osi_level_8/profile11/evaluator"
require_relative "rails_osi_level_8/intent/projection"
require_relative "rails_osi_level_8/intent/graph_store"
require_relative "rails_osi_level_8/intent/validator"
require_relative "rails_osi_level_8/intent/grounding"
require_relative "rails_osi_level_8/intent/trace_gate"
require_relative "rails_osi_level_8/cpcp_adapter"

module RailsOsiLevel8; end

OsiLevel8 = RailsOsiLevel8 unless defined?(OsiLevel8)

if defined?(::ActiveRecord::Base)
  require_relative "rails_osi_level_8/models/record"
  require_relative "rails_osi_level_8/models/governed_record"
  require_relative "rails_osi_level_8/models/context"
  require_relative "rails_osi_level_8/models/cyborg_channel"
  require_relative "rails_osi_level_8/models/operation_request"
  require_relative "rails_osi_level_8/models/operation_journal_entry"
  require_relative "rails_osi_level_8/models/execution_receipt"
  require_relative "rails_osi_level_8/models/admission_attempt"
  require_relative "rails_osi_level_8/models/reference_pass"
  require_relative "rails_osi_level_8/models/routing_decision"
  require_relative "rails_osi_level_8/models/routing_hop"
  require_relative "rails_osi_level_8/models/authorization_evidence"
  require_relative "rails_osi_level_8/models/observation"
  require_relative "rails_osi_level_8/models/outcome"
  require_relative "rails_osi_level_8/models/learning_event"
  require_relative "rails_osi_level_8/models/ux"
  require_relative "rails_osi_level_8/models/meaning"
  require_relative "rails_osi_level_8/models/profile_evidence"
  require_relative "rails_osi_level_8/models/biography_event"
  require_relative "rails_osi_level_8/models/provenance_edge"
  require_relative "rails_osi_level_8/intent/immutable"
  require_relative "rails_osi_level_8/intent/models/record"
  require_relative "rails_osi_level_8/intent/models/stakeholder"
  require_relative "rails_osi_level_8/intent/models/value_proposition"
  require_relative "rails_osi_level_8/intent/models/offer"
  require_relative "rails_osi_level_8/intent/models/market_segment"
  require_relative "rails_osi_level_8/intent/models/economic_actor"
  require_relative "rails_osi_level_8/intent/models/exchange_relationship"
  require_relative "rails_osi_level_8/intent/models/goal"
  require_relative "rails_osi_level_8/intent/models/key_result"
  require_relative "rails_osi_level_8/intent/models/outcome"
  require_relative "rails_osi_level_8/intent/models/value_metric"
  require_relative "rails_osi_level_8/intent/models/constraint"
  require_relative "rails_osi_level_8/intent/models/externality"
  require_relative "rails_osi_level_8/intent/pulls"
  require_relative "rails_osi_level_8/intent/factory"
  require_relative "rails_osi_level_8/profile_index"
  require_relative "rails_osi_level_8/authorization"
  require_relative "rails_osi_level_8/routing"
  require_relative "rails_osi_level_8/references"
  require_relative "rails_osi_level_8/learning"
  require_relative "rails_osi_level_8/p7_commands"
  require_relative "rails_osi_level_8/projections"
  require_relative "rails_osi_level_8/fixtures"
end

require_relative "rails_osi_level_8/engine" if defined?(::Rails::Engine)
