# frozen_string_literal: true

require "date"
require "digest"
require "fileutils"
require "yaml"

module Vv
  module DependencyOrch
    # Overlays: what each website still owes the substrate, filed twice.
    #
    # This is the same model the rest of the gem runs on, pointed at documents
    # instead of images. ONE IDENTITY, MANY PLACEMENTS: the identity is the
    # overlay file in the website's own repository, and the cuts here are
    # placements of it. That is why only `capability/` holds bytes and every
    # other cut holds a summary with links. Copying the file into four folders
    # would give one overlay four identities, and the first time somebody
    # edited the wrong copy this tree would be asserting two different things
    # about the same layer -- the exact defect FLOOR.json was written to stop.
    #
    # THE SOURCES ARE NEVER WRITTEN TO. Rollout reads the websites and writes
    # only under this gem's docs/overlays. An orchestrator that edits the
    # repositories it is describing cannot be run to find out what is true.
    module Overlays
      SPINE_FILE = "_spine.yml"
      SITES_FILE = "_sites.yml"
      MANIFEST_FILE = "_manifest.yml"
      SUMMARY_FILE = "_summary.md"
      INDEX_FILE = "_index.md"

      CAPABILITY = "capability"
      IMPLEMENTATION = "implementation"

      # The implementation cut's three facets. `gem` has no closed vocabulary
      # -- a website may depend on any gem -- so it is derived from what the
      # sites declare, while `image` and `type` are checked against the spine.
      FACETS = {
        image: { dir: "by-image", key: :images, vocabulary: "images", per_site: true },
        gem: { dir: "by-gem", key: :gems, vocabulary: nil, per_site: false },
        type: { dir: "by-type", key: :types, vocabulary: "types", per_site: false }
      }.freeze

      GENERATED = "<!-- generated by `rake orch:overlays:rollout` -- do not edit -->"

      module_function

      # ---------------------------------------------------------------- read

      def tree(root) = File.join(File.expand_path(root), "docs", "overlays")

      def spine_path(root) = File.join(tree(root), SPINE_FILE)

      def sites_path(root, override = nil)
        return File.expand_path(override) if override && !override.to_s.empty?

        File.join(tree(root), SITES_FILE)
      end

      def load_spine(root:)
        path = spine_path(root)
        return Envelope.refuse("not_indexed", "no spine at #{path}; nothing defines the slots") unless File.file?(path)

        Envelope.never_raise do
          data = YAML.safe_load(File.read(path)) || {}
          Envelope.ok(
            path: path,
            slots: rows(data["slots"]),
            types: rows(data["types"]),
            images: rows(data["images"])
          )
        end
      end

      def load_sites(root:, override: nil)
        path = sites_path(root, override)
        return Envelope.refuse("not_indexed", "no site manifest at #{path}") unless File.file?(path)

        Envelope.never_raise do
          data = YAML.safe_load(File.read(path)) || {}
          gem_root = File.expand_path(root)
          sites = rows(data["sites"]).map do |site|
            base = File.expand_path(site[:path].to_s.sub(/\A~/, Dir.home), gem_root)
            site.merge(root: base, overlays_dir: File.join(base, site[:overlays] || "docs/overlays"))
          end
          Envelope.ok(path: path, sites: sites)
        end
      end

      # Every overlay both websites declare, filed onto the spine.
      #
      # Findings come back in `unfiled` rather than as a refusal. A site that
      # forgot a facet key has not made the other fifteen overlays unreadable,
      # and refusing the whole collection would mean the one command that could
      # show you the mistake is the one that will not run until you fix it.
      def collect(root:, sites_override: nil)
        spine = load_spine(root: root)
        return spine unless spine[:ok]

        sites = load_sites(root: root, override: sites_override)
        return sites unless sites[:ok]

        Envelope.never_raise do
          notes = []
          entries = []

          sites[:sites].each do |site|
            dir = site[:overlays_dir]
            unless Dir.exist?(dir)
              notes << { reason: "not_indexed",
                         because: "#{site[:key]}: no overlay directory at #{dir}" }
              next
            end
            overlay_files(dir).each { |path| entries << entry_for(site, path, dir) }
          end

          filed, unfiled = triage(entries, spine)

          Envelope.ok(
            root: File.expand_path(root),
            spine_path: spine[:path],
            sites_path: sites[:path],
            sites: sites[:sites].map { |s| s.slice(:key, :title, :root, :overlays_dir, :because) },
            slots: facet_groups(spine[:slots], filed) { |entry, slot| entry[:slot] == slot[:id] },
            images: facet_groups(spine[:images], filed) { |e, img| e[:images].include?(img[:id]) },
            types: facet_groups(spine[:types], filed) { |e, type| e[:types].include?(type[:id]) },
            gems: gem_groups(filed),
            filed: filed,
            unfiled: unfiled,
            notes: notes
          )
        end
      end

      def overlay_files(dir)
        Dir.glob(File.join(dir, "*.md")).sort.reject do |path|
          name = File.basename(path)
          name.start_with?("_") || name == "index.md"
        end
      end

      def entry_for(site, path, dir)
        parsed = parse(path)
        front = parsed[:frontmatter]
        body = parsed[:body]
        {
          site: site[:key],
          site_title: site[:title],
          file: File.basename(path),
          path: path,
          source: File.join(site[:overlays] || "docs/overlays", File.basename(path)),
          sha256: Digest::SHA256.hexdigest(File.binread(path)),
          title: string(front["title"]),
          description: string(front["description"]),
          status: string(front["status"]),
          slot: string(front["overlay_slot"]),
          types: list(front["overlay_types"]),
          images: list(front["images"]),
          gems: list(front["gems"]),
          substrate_refs: list(front["substrate_refs"]),
          headings: headings(body),
          acceptance: acceptance_count(body),
          parse_error: parsed[:error]
        }.tap { |e| e[:dir] = dir }
      end

      # An overlay is filed only if every facet it declares is one the spine
      # knows. A half-filed overlay -- good slot, invented image -- is the
      # worst outcome available: it appears in the capability cut, looks
      # complete, and is silently missing from the cut somebody deploys from.
      def triage(entries, spine)
        slot_ids = spine[:slots].map { |s| s[:id] }
        image_ids = spine[:images].map { |i| i[:id] }
        type_ids = spine[:types].map { |t| t[:id] }

        filed = []
        unfiled = []
        entries.each do |entry|
          bad = facet_faults(entry, slot_ids, image_ids, type_ids)
          if bad
            unfiled << entry.merge(bad)
          else
            filed << entry
          end
        end
        [filed.sort_by { |e| [e[:slot], e[:site], e[:file]] }, unfiled.sort_by { |e| [e[:site], e[:file]] }]
      end

      def facet_faults(entry, slot_ids, image_ids, type_ids)
        if entry[:slot].empty?
          return { reason: "slot_undeclared",
                   because: "#{entry[:site]}/#{entry[:file]} declares no overlay_slot" }
        end
        unless slot_ids.include?(entry[:slot])
          return { reason: "no_such_slot",
                   because: "#{entry[:site]}/#{entry[:file]} declares slot #{entry[:slot].inspect}; " \
                            "the spine defines #{slot_ids.join(', ')}" }
        end

        stray_images = entry[:images] - image_ids
        stray_types = entry[:types] - type_ids
        return nil if stray_images.empty? && stray_types.empty?

        { reason: "no_such_facet",
          because: "#{entry[:site]}/#{entry[:file]} declares " \
                   "#{(stray_images.map { |i| "image #{i.inspect}" } +
                       stray_types.map { |t| "overlay type #{t.inspect}" }).join(', ')}, " \
                   "which the spine does not define" }
      end

      def facet_groups(vocabulary, filed)
        vocabulary.map do |row|
          row.merge(entries: filed.select { |entry| yield(entry, row) })
        end
      end

      # Gems are open vocabulary, so this facet is derived. Sorted by how many
      # overlays name the gem, because that ordering is the one fact this cut
      # produces that neither website could have stated on its own.
      def gem_groups(filed)
        filed.flat_map { |e| e[:gems] }.uniq.sort.map do |name|
          entries = filed.select { |e| e[:gems].include?(name) }
          { id: name, title: name, entries: entries }
        end.sort_by { |g| [-g[:entries].length, g[:id]] }
      end

      # -------------------------------------------------------------- write

      # Roll the websites' overlays into both cuts.
      #
      # `prune` removes mirrors whose source is gone. It is on by default and
      # only ever deletes inside the two generated directories: a rename in a
      # website would otherwise leave the old file here forever, still
      # readable, still summarised, describing a layer nobody is building.
      def rollout(root:, sites_override: nil, prune: true)
        collected = collect(root: root, sites_override: sites_override)
        return collected unless collected[:ok]

        Envelope.never_raise do
          base = tree(root)
          written = []
          kept = {}

          written.concat(write_capability(base, collected, kept))
          written.concat(write_implementation(base, collected, kept))
          written.concat(write_manifest(base, collected, kept))

          removed = prune ? prune_tree(base, kept) : []
          collected.merge(wrote: written.sort, removed: removed.sort, pruned: prune)
        end
      end

      def write_capability(base, collected, kept)
        written = []
        collected[:slots].each do |slot|
          dir = File.join(base, CAPABILITY, slot[:id])
          slot[:entries].each do |entry|
            dest = File.join(dir, entry[:site], entry[:file])
            written << put(dest, File.binread(entry[:path]), kept, base)
          end
          written << put(File.join(dir, SUMMARY_FILE), slot_summary(slot, collected), kept, base)
        end
        written << put(File.join(base, CAPABILITY, INDEX_FILE), capability_index(collected), kept, base)
        written.compact
      end

      def write_implementation(base, collected, kept)
        written = []
        FACETS.each do |facet, spec|
          groups = collected[spec[:key]]
          groups.each do |group|
            dir = File.join(base, IMPLEMENTATION, spec[:dir], slugify(group[:id]))
            written << put(File.join(dir, SUMMARY_FILE), facet_summary(facet, group, collected), kept, base)
            next unless spec[:per_site]

            group[:entries].group_by { |e| e[:site] }.each do |site, entries|
              written << put(File.join(dir, site, SUMMARY_FILE),
                             image_site_summary(group, site, entries, collected), kept, base)
            end
          end
          written << put(File.join(base, IMPLEMENTATION, spec[:dir], INDEX_FILE),
                         facet_index(facet, groups, collected), kept, base)
        end
        written << put(File.join(base, IMPLEMENTATION, INDEX_FILE), implementation_index(collected), kept, base)
        written.compact
      end

      def write_manifest(base, collected, kept)
        body = {
          "version" => 1,
          "what" => "Written by rake orch:overlays:rollout. The sha256 of each site source at " \
                    "rollout time; orch:overlays:check compares it to both ends.",
          "spine" => relative(base, collected[:spine_path]),
          "sites" => relative(base, collected[:sites_path]),
          "mirrors" => collected[:slots].flat_map do |slot|
            slot[:entries].map do |entry|
              {
                "slot" => slot[:id],
                "site" => entry[:site],
                "source" => File.join(entry[:site], entry[:source]),
                "source_path" => entry[:path],
                "mirror" => File.join(CAPABILITY, slot[:id], entry[:site], entry[:file]),
                "sha256" => entry[:sha256]
              }
            end
          end
        }
        [put(File.join(base, MANIFEST_FILE), "#{body.to_yaml}", kept, base)].compact
      end

      # Idempotent by content. Returning nil for an unchanged file is what lets
      # `wrote` mean "this rollout changed something" rather than "this rollout
      # ran", which is the difference between a useful CI diff and a daily
      # commit that says nothing.
      def put(dest, content, kept, base)
        kept[dest] = true
        return nil if File.file?(dest) && File.binread(dest) == content

        FileUtils.mkdir_p(File.dirname(dest))
        File.binwrite(dest, content)
        relative(base, dest)
      end

      def prune_tree(base, kept)
        removed = []
        [CAPABILITY, IMPLEMENTATION].each do |top|
          dir = File.join(base, top)
          next unless Dir.exist?(dir)

          Dir.glob(File.join(dir, "**", "*")).sort.reverse_each do |path|
            if File.file?(path) && !kept[path]
              File.delete(path)
              removed << relative(base, path)
            elsif File.directory?(path) && (Dir.entries(path) - %w[. ..]).empty?
              Dir.rmdir(path)
            end
          end
        end
        removed
      end

      # -------------------------------------------------------------- check

      def check(root:, sites_override: nil)
        collected = collect(root: root, sites_override: sites_override)
        return collected unless collected[:ok]

        base = tree(root)
        manifest = File.join(base, MANIFEST_FILE)
        unless File.file?(manifest)
          return Envelope.refuse("overlays_stale", "no #{MANIFEST_FILE}; this tree has never been rolled out")
        end

        Envelope.never_raise do
          recorded = YAML.safe_load(File.read(manifest)) || {}
          findings = findings_for(base, Array(recorded["mirrors"]), collected)

          if findings.empty?
            Envelope.ok(checked: Array(recorded["mirrors"]).length, findings: [], notes: collected[:notes])
          else
            worst = findings.any? { |f| f[:finding] == "mirror_edited" } ? "mirror_edited" : "overlays_stale"
            Envelope.refuse(worst, summarise(findings))
              .merge(findings: findings, notes: collected[:notes])
          end
        end
      end

      def findings_for(base, recorded, collected)
        live = collected[:filed].to_h { |e| [File.join(e[:site], e[:source]), e] }
        findings = []

        recorded.each do |row|
          mirror = File.join(base, row["mirror"].to_s)
          entry = live[row["source"].to_s]

          if entry.nil?
            findings << finding("orphaned", row["mirror"],
                                "the site no longer declares #{row['source']}; rollout will remove this mirror")
            next
          end
          unless File.file?(mirror)
            findings << finding("missing", row["mirror"], "rolled-out file is gone; rollout will restore it")
            next
          end

          mirrored = Digest::SHA256.hexdigest(File.binread(mirror))
          if mirrored != row["sha256"]
            findings << finding("mirror_edited", row["mirror"],
                                "edited in place. The original is #{row['source']} -- copy the change there " \
                                "before rolling out, or rollout will overwrite it")
          elsif entry[:sha256] != row["sha256"]
            findings << finding("stale", row["mirror"], "#{row['source']} has moved since the last rollout")
          end
        end

        known = recorded.map { |r| r["source"].to_s }
        (live.keys - known).sort.each do |source|
          findings << finding("unrolled", source, "declared by the site and not in this tree")
        end
        findings
      end

      def finding(kind, at, because) = { finding: kind, at: at.to_s, because: because }

      def summarise(findings)
        findings.group_by { |f| f[:finding] }
                .map { |kind, rows| "#{rows.length} #{kind}" }
                .join(", ") + "; run rake orch:overlays:rollout"
      end

      # ------------------------------------------------------------ markdown

      def slot_summary(slot, collected)
        sites = collected[:sites]
        present = slot[:entries].map { |e| e[:site] }.uniq
        out = [GENERATED, "", "# #{slot[:id]} · #{slot[:title]}", "", wrap(slot[:capability]), ""]
        out += ["> **Why here.** #{wrap(slot[:why_here])}", ""] unless slot[:why_here].to_s.empty?

        out += ["## Who needs this", ""]
        if slot[:entries].empty?
          out << "Nothing is filed at this slot. That is a statement about the two websites, not about the capability."
        else
          out << "| Site | Overlay | Status | Type | Image | Acceptance |"
          out << "|---|---|---|---|---|---|"
          slot[:entries].each do |e|
            out << "| #{e[:site]} | [#{e[:title]}](#{e[:site]}/#{e[:file]}) | #{e[:status]} | " \
                   "#{e[:types].join(', ')} | #{e[:images].join(', ')} | #{e[:acceptance]} |"
          end
        end
        out << ""

        silent = sites.map { |s| s[:key] } - present
        unless silent.empty?
          out += ["**Silent here:** #{silent.join(', ')}. Silence is a site that has not written this " \
                  "layer down, not a site that does not need it.", ""]
        end

        unless slot[:entries].empty?
          out += ["## What each site says", ""]
          slot[:entries].each do |e|
            out << "### #{e[:site]} — #{e[:title]}"
            out << ""
            out << wrap(e[:description]) unless e[:description].empty?
            out << ""
            out << "Source: `#{e[:site]}/#{e[:source]}`. Sections: #{e[:headings].join(' · ')}."
            out << ""
          end
        end

        out += ["---", "", "The files here are copies. Edit the source in each website's `docs/overlays/`, " \
                "then `rake orch:overlays:rollout`."]
        "#{out.join("\n").rstrip}\n"
      end

      def facet_summary(facet, group, collected)
        out = [GENERATED, "", "# #{group[:title] || group[:id]}", ""]
        out += [wrap(group[:means]), ""] unless group[:means].to_s.empty?
        out += ["**Owner:** #{group[:owner]}", ""] unless group[:owner].to_s.empty?
        if group[:floor]
          out += ["**Floor:** `#{group[:floor]}` — `#{group[:image]}`",
                  "**Digest when written:** `#{group[:digest_when_written]}` " \
                  "(#{Array(group[:platforms]).join(', ')})", ""]
        end

        out += ["## Overlays", ""]
        if group[:entries].empty?
          out << "None."
        else
          out << "| Site | Overlay | Slot | Status |"
          out << "|---|---|---|---|"
          group[:entries].sort_by { |e| [e[:site], e[:slot]] }.each do |e|
            out << "| #{e[:site]} | #{link_to_capability(e, 3)} | #{e[:slot]} | #{e[:status]} |"
          end
        end
        out += ["", "#{group[:entries].length} overlay(s) across " \
                    "#{group[:entries].map { |e| e[:site] }.uniq.length} site(s).", ""]
        out += cut_footer(facet)
        "#{out.join("\n").rstrip}\n"
      end

      def image_site_summary(group, site, entries, collected)
        title = collected[:sites].find { |s| s[:key] == site }&.dig(:title) || site
        out = [GENERATED, "", "# #{group[:title] || group[:id]} · #{site}", "",
               "What **#{title}** needs from `#{group[:id]}`.", ""]
        out << "| Slot | Overlay | Type | Status | Gems |"
        out << "|---|---|---|---|---|"
        entries.sort_by { |e| e[:slot] }.each do |e|
          out << "| #{e[:slot]} | #{link_to_capability(e, 4)} | #{e[:types].join(', ')} | " \
                 "#{e[:status]} | #{e[:gems].empty? ? '—' : e[:gems].join(', ')} |"
        end
        out += ["", "## Substrate named by these overlays", ""]
        refs = entries.flat_map { |e| e[:substrate_refs] }.uniq.sort
        out << (refs.empty? ? "None beyond the gems above." : refs.map { |r| "* `#{r}`" }.join("\n"))
        out += ["", *cut_footer(:image)]
        "#{out.join("\n").rstrip}\n"
      end

      def capability_index(collected)
        out = [GENERATED, "", "# Overlays by capability", "",
               wrap("One slot per capability a website's overlay has to make true, and the " \
                    "overlays each site filed against it. The numbers are a dependency order, " \
                    "not a delivery order."), "",
               "| Slot | Capability | #{collected[:sites].map { |s| s[:key] }.join(' | ')} |",
               "|---|---|#{collected[:sites].map { '---' }.join('|')}|"]
        collected[:slots].each do |slot|
          cells = collected[:sites].map do |site|
            n = slot[:entries].count { |e| e[:site] == site[:key] }
            n.zero? ? "—" : n.to_s
          end
          out << "| [#{slot[:id]}](#{slot[:id]}/#{SUMMARY_FILE}) | #{slot[:title]} | #{cells.join(' | ')} |"
        end
        out += ["", "Generated from `#{relative(tree_of(collected), collected[:spine_path])}`."]
        "#{out.join("\n").rstrip}\n"
      end

      def facet_index(facet, groups, collected)
        heading = { image: "by image", gem: "by gem / module", type: "by override type" }[facet]
        out = [GENERATED, "", "# Overlays #{heading}", "",
               "| #{facet.to_s.capitalize} | Overlays | Sites |", "|---|---|---|"]
        groups.each do |group|
          out << "| [#{group[:title] || group[:id]}](#{slugify(group[:id])}/#{SUMMARY_FILE}) | " \
                 "#{group[:entries].length} | #{group[:entries].map { |e| e[:site] }.uniq.sort.join(', ')} |"
        end
        out += ["", *cut_footer(facet)]
        "#{out.join("\n").rstrip}\n"
      end

      def implementation_index(collected)
        out = [GENERATED, "", "# Overlays by implementation", "",
               wrap("The same #{collected[:filed].length} overlays as the capability cut, sliced by what " \
                    "they land on rather than by what they make true. Three facets: the image they " \
                    "build FROM, the gems they touch, and the kind of override they are."), "",
               "* [By image](#{FACETS[:image][:dir]}/#{INDEX_FILE}) — " \
               "#{collected[:images].length} images, per site",
               "* [By gem / module](#{FACETS[:gem][:dir]}/#{INDEX_FILE}) — " \
               "#{collected[:gems].length} gems",
               "* [By override type](#{FACETS[:type][:dir]}/#{INDEX_FILE}) — " \
               "#{collected[:types].length} types", "",
               "## Who owns the work", "", "| Type | Owner | Overlays |", "|---|---|---|"]
        collected[:types].each do |type|
          out << "| #{type[:title]} | #{type[:owner]} | #{type[:entries].length} |"
        end
        out += ["", *cut_footer(:type)]
        "#{out.join("\n").rstrip}\n"
      end

      def cut_footer(_facet)
        ["---", "",
         "This cut holds summaries, not copies. The one mirrored copy of every overlay lives under " \
         "`capability/`, and the original lives in the website. Three places holding the same bytes " \
         "is three things that can disagree."]
      end

      def link_to_capability(entry, depth)
        "[#{entry[:title]}](#{'../' * depth}#{CAPABILITY}/#{entry[:slot]}/#{entry[:site]}/#{entry[:file]})"
      end

      # ------------------------------------------------------------ parsing

      # A minimal frontmatter reader. vv-per-site has a better one and this gem
      # will not use it: that parser arrives with ActiveRecord behind it, and
      # the rule this gem holds above all others is that nothing below
      # dependency_orch.rb loads Rails. spec/gates_spec.rb enforces it.
      def parse(path)
        text = File.read(path).sub(/\A﻿/, "")
        return { frontmatter: {}, body: text, error: nil } unless text.start_with?("---")

        _pre, raw, rest = text.split(/^---\s*$/, 3)
        return { frontmatter: {}, body: text, error: nil } if rest.nil?

        front = YAML.safe_load(raw.to_s, permitted_classes: [Date, Time], aliases: true) || {}
        { frontmatter: front.is_a?(Hash) ? front : {}, body: rest.sub(/\A\s*\n/, ""), error: nil }
      rescue Psych::Exception => e
        { frontmatter: {}, body: "", error: "#{e.class}: #{e.message}" }
      end

      def headings(body)
        body.to_s.lines.filter_map { |line| line.match(/^\#{1,3}\s+(.+?)\s*$/)&.captures&.first }
      end

      # Counted rather than parsed. The number is a weak signal and is offered
      # as one: an overlay is done when its acceptance list HOLDS (ADR 0073),
      # which no count can tell you. What it does catch is the overlay that
      # declares none at all.
      def acceptance_count(body)
        inside = false
        body.to_s.lines.count do |line|
          if (m = line.match(/^\#{1,3}\s+(.+?)\s*$/))
            inside = m[1].strip.casecmp("acceptance").zero?
            false
          else
            inside && line.match?(/^\s*[*-]\s+\S/)
          end
        end
      end

      # ------------------------------------------------------------- shared

      def rows(value)
        Array(value).select { |row| row.is_a?(Hash) }.map do |row|
          row.to_h { |k, v| [k.to_sym, v] }
        end
      end

      def string(value) = value.to_s.strip

      def list(value) = Array(value).map { |v| v.to_s.strip }.reject(&:empty?)

      def slugify(value) = value.to_s.downcase.gsub(/[^a-z0-9.]+/, "-").gsub(/\A-|-\z/, "")

      def relative(base, path)
        expanded = File.expand_path(path.to_s)
        prefix = "#{File.expand_path(base)}/"
        expanded.start_with?(prefix) ? expanded.delete_prefix(prefix) : expanded
      end

      def tree_of(collected) = tree(collected[:root])

      # Frontmatter is folded prose; these summaries are read in a terminal and
      # in a diff. Re-wrapping keeps a one-line YAML description from becoming
      # a 400-column table cell.
      def wrap(text, width = 78)
        words = text.to_s.split
        return "" if words.empty?

        words.drop(1).each_with_object([words.first.dup]) do |word, lines|
          if lines.last.length + word.length + 1 > width
            lines << word.dup
          else
            lines.last << " " << word
          end
        end.join("\n")
      end
    end
  end
end
